config/routes.rb
Rails.application.routes.draw do

  get 'test/index'

  get 'resorts/index'

  get '/', to: 'landing#index'
  get '/auth/google_oauth2', as: :login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :dashboard, only: [:index]
  resources :resorts,   only: [:index, :create, :destroy]
  resources :sessions,  only: [:edit, :update]
  resources :test,  only: [:index]

end

app/models/resort.rb
class Resort < ActiveRecord::Base
  belongs_to :user

  # after_save :set_zip
  #
  # def set_zip
  #   zip = GeocodingService.new.zip(self[:latitude].to_f, self[:longitude].to_f)
  #   self.update_attributes(zip_code: zip)
  # end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :resorts

  def self.find_or_create_from_oauth(oauth)
    user = User.find_or_create_by(provider: oauth.provider, uid: oauth.uid)
    user.name       = oauth.info.name
    user.uid        = oauth.uid
    user.provider   = oauth.provider
    user.email      = oauth.info.email
    user.token      = oauth.credentials.token
    user.first_name = oauth.info.first_name
    user.last_name  = oauth.info.last_name
    user.image_url  = oauth.info.image
    user.save

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @presenter = DashboardPresenter.new(current_user)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController

  def index
    @results ||= trailapi_service.search_results(params)
  end

  def create
    @resort = Resort.new(
                    name:          params[:name],
                    official_name: params[:official_name],
                    state:         params[:state],
                    description:   params[:description],
                    latitude:      params[:latitude],
                    longitude:     params[:longitude],
                    user_id:       params[:user_id].to_i,
                    zip_code:      geocoding_service.zip(params[:latitude].to_f, params[:longitude].to_f)
                    )

    if @resort.save
      redirect_to dashboard_index_path
      flash[:success] = "#{@resort.official_name} has been added to your dashboard."
    else
      redirect_to '/'
      flash[:error] = "Uh-oh, something went wrong."
    end
  end

  def destroy
    resort = Resort.find(params[:id])
    resort.delete
    flash[:deleted] = "You have removed #{resort.name} from your dashboard"
    redirect_to dashboard_index_path
  end


  private
  def trailapi_service
    TrailapiService.new
  end

  def geocoding_service
    GeocodingService.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_oauth(request.env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      redirect_to dashboard_index_path
    else
      redirect_to "/"
    end
  end

  def edit
    user = User.find(params[:id])
    if user.update_attributes(phone_number: "#{params[:phone_number]}")
      redirect_to dashboard_index_path
      flash[:success] = "You have successfully added a number to your account."
      twilio_service.welcome_message(params[:phone_number])
    else
      redirect_to dashboard_index_path
      flash[:error] = "You must enter a valid phone #."
    end
  end

  def destroy
    session.clear
    redirect_to "/"
  end

  private

  def twilio_service
    TwilioService.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper


end

app/helpers/json_helper.rb
module JsonHelper

  def parse_json(response)
    JSON.parse(response.body, symbolize_names: true)
  end

end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboard/index.html.erb
<body class="dash-bkg">

<h1 class="text-center" id="dash-header"><%= current_user.name %>'s Dashboard</h1>
<div class="show-snow text-center">
  <% unless current_user.resorts == [] %>
    <button type="button" class="btn btn-default btn-lg">
      <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span> Snow Report
    </button>
  <% end %>
</div><br>
<div class="overlay hidden">
  <button type="button" class="btn btn-warning">X</button>
    <%= render partial: 'partials/snow_graph' %>
</div>
<div class="row">
  <%= render partial: 'partials/resort_search' %>
  <% unless current_user.phone_number %>
    <%= render partial: 'partials/phone_number_form' %>
  <% end %>
</div><br><br>
<% if current_user.resorts == [] %>
  <h3 class="text-center" id="dash-header">Your dashboard is empty add your favorite resorts to begin playing</h3>
<% else %>
  <div class="resorts">
    <%= render partial: 'partials/users_resorts' %>
  </div>
<% end %>

<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>

</body>

app/views/landing/index.html.erb
<body class="landing">

  <div class="text-center">
    <h1 class="white-text">Customize your snow report!</h1>
    <p>C'mon, do it!</p>
  </div>
  
  <div class="text-center">
    <%= link_to "Login with Google", login_path , class:"btn btn-success"%>
  </div>

</body>

app/views/layouts/application.html.erb
<html>

<head>
  <title>SnowDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/nav" %>
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
        <%= value %>
  </div>
<% end %>

<%= yield %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>

</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header"><a class="navbar-brand navbar-link" href="#"><span class="glyphicon glyphicon-camera"></span>Snow Dashboard</a>
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        </div>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li role="presentation"><%= link_to "Dashboard", dashboard_index_path %></li>
                <li role="presentation"><%= link_to "Logout", logout_path %></li>
              <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/partials/_phone_number_form.html.erb
<div class="col-md-4 phone-form">
  <h3>Add a phone # to receive text alerts</h3>
  <%= form_tag edit_session_path(id: current_user.id), method: :get do %>
    <%= label_tag :phone_number %>
    <%= text_field_tag :phone_number %>
    <%= submit_tag "Add Number", class:"btn btn-success" %>
  <% end %>
  <br>
</div>

app/views/partials/_resort_search.html.erb
<div class="col-md-5 resort-search">
  <h3 class="center white">Add a ski area to your dashboard</h3>
  <%= form_tag resorts_path, method: :get do %>
    <%= select_tag :state, options_for_select(@presenter.states)%>
    <%= text_field_tag :city, nil, placeholder: 'City' %>
    <%= text_field_tag :resort_name, nil, placeholder: 'Resort name' %>
    <%= submit_tag "Search", class:"btn btn-success" %>
  <% end %>
</div>

app/views/partials/_search_results.html.erb
<h2>Search Results</h2>

<% if @results.count == 0 %>
  <h3>No results match your criteria. Please try another search.</h3>
<% else %>
  <% @results.each do |result| %>
    <ul>
      <li><%= result[:name] %></li>
      <li><%= result[:official_name] %></li>
      <li><%= result[:state] %></li>
      <li><%= result[:description] %></li>
      <%= form_tag resorts_path, method: :post do %>
        <%= hidden_field_tag(:name, result[:name]) %>
        <%= hidden_field_tag(:official_name, result[:official_name]) %>
        <%= hidden_field_tag(:state, result[:state]) %>
        <%= hidden_field_tag(:description, result[:description]) %>
        <%= hidden_field_tag(:latitude, result[:latitude]) %>
        <%= hidden_field_tag(:longitude, result[:longitude]) %>
        <%= hidden_field_tag(:type, result[:type]) %>
        <%= hidden_field_tag(:user_id, current_user.id) %>
        <%= submit_tag "Add to Dashboard", method: :post %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/partials/_snow_graph.html.erb
<%= high_chart_globals(@presenter.chart_globals) %>
<%= high_chart("some_id", @presenter.chart) %>

app/views/partials/_users_resorts.html.erb
<div class="row">
  <% @presenter.resorts.each_with_index do |resort, index| %>
    <div class="col-md-5 center resort-card">
        <%= link_to "X", resort_path(resort.id), method: :delete, class: "btn btn-danger" %>
        <h3 class="text-center"><%= resort.official_name %></h3>
        <div class="resort-title">
            <div class="col-md-4 col-sm-4">
              <div class="thumbnail">
                <h4 class="text-center">Today</h4>
                <%= image_tag "#{@presenter.forecast[index][0][:icon]}.png", class: "thumbnail"%>
                <p class="text-center"><%= @presenter.forecast[index][0][:summary] %></p>
              </div>
                <ul class="list-unstyled">
                    <li>Max: <%= @presenter.forecast[index][0][:max_temp] %> </li>
                    <li>Min: <%= @presenter.forecast[index][0][:min_temp] %></li>
                    <li>Prob: <%= @presenter.forecast[index][0][:precip_prob] %> </li>
                    <li>Hum: <%= @presenter.forecast[index][0][:humidity] %> </li>
                </ul>
          </div>
            <div class="col-md-4 col-sm-4">
              <div class="thumbnail">
                <h4 class="text-center"><%= DateTime.tomorrow.strftime("%A") %></h4>
                <%= image_tag "#{@presenter.forecast[index][1][:icon]}.png", class: "thumbnail"%>
                <p class="text-center"><%= @presenter.forecast[index][1][:summary] %></p>
              </div>
                <ul class="list-unstyled">
                    <li>Max: <%= @presenter.forecast[index][1][:max_temp] %> </li>
                    <li>Min: <%= @presenter.forecast[index][1][:min_temp] %></li>
                    <li>Prob: <%= @presenter.forecast[index][1][:precip_prob] %> </li>
                    <li>Hum: <%= @presenter.forecast[index][1][:humidity] %> </li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="thumbnail">
                  <h4 class="text-center"><%= (DateTime.tomorrow + 1).strftime("%A") %></h4>
                  <%= image_tag "#{@presenter.forecast[index][2][:icon]}.png", class: "thumbnail"%>
                  <p class="text-center"><%= @presenter.forecast[index][2][:summary] %></p>
                </div>
                <ul class="list-unstyled">
                    <li>Max: <%= @presenter.forecast[index][2][:max_temp] %> </li>
                    <li>Min: <%= @presenter.forecast[index][2][:min_temp] %></li>
                    <li>Prob: <%= @presenter.forecast[index][2][:precip_prob] %> </li>
                    <li>Hum: <%= @presenter.forecast[index][2][:humidity] %> </li>
                </ul><br>
            </div>
              <div class="mtn-desc text-center">
                <p><%= truncate(resort[:description], length: 275) %></p>
              </div>
        </div>
    </div>
  <% end %>

</div>

app/views/resorts/index.html.erb
<%= render partial: 'partials/search_results', :locals => {:results => @results} %>